---
layout: cv
title: Isaac Newtons's CV
---
# Gavin Tucker
Computer Scientist, Buisness Analylist, Data Scientist.

<!-- <div id="webaddress">
<a href="isaac@applesdofall.org">isaac@applesdofall.org</a>
| <a href="http://en.wikipedia.org/wiki/Isaac_Newton">My wikipedia page</a>
</div> -->

## Education

Bachelor of Science in Computer Science                            (Winter 2025 Rexburg, ID)
Brigham Young University-Idaho
• GPA: 3.91 
• Computer Science Society
• Minor in Business Analytics and DataScience
• Brigham Young University Idaho Scholarship

### Work Experience

Cashier                                                          (May 2019 – Jun. 2021 Burlington,NC)
Chick-fil-A

• Greeted customers at the counter to fulfill orders and answer questions
• Distributed to customer satisfaction with an average of 20 orders given per hour
• Built connections with customers, resulting in an 80% satisfaction rate at that franchise
• Handled cash transactions and point-of-sale operations

Skilled Labor                                                               June. 2021-Sep. 2021 
Elite Garage                                                                High Point, NC

• Worked independently to meet productivity and quality expectations
• Distributed materials and tools from storage facilities to worksite
• Followed instructions and safety protocols to prevent accidents and injuries

Tutor – Team Lead                                                           Feb. 2024 – Present 
Study Buddies BYUI                                                          Rexburg, ID

• Created study plans and strategies for students success
• Approved time submissions
• Did individual interviews, presentations, and corrective actions
• Participated in an Arbinger Program where we read Dangerous Love and Outward Mindset

### Volunteer Experience

Full-Time Volunteer Representative                                           Sep. 2021 – Aug. 2023
The Church of Jesus Christ of Latter-day Saints                              Colombia, Medellin

• Lived and worked with a variety of people from different backgrounds
• Planned meetings, took care of finances, and sent in weekly reports
• Helped support local leaders in communities, spoke publicly frequently, and helped plan activities

## Awards / Skills

• Eagle Scout
• Fluent in Spanish
• Proficient in Python, HTML, CSS, and SQL
• Now learning Linux, Java and C#





<!-- ### Footer

Last updated: May 2013 -->



<!-- ### Footer

Last updated: May 2013 -->